name: .NET 8 CI with Redis and Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests and collect coverage
      run: dotnet test UseRedisCache.Tests/UseRedisCache.Tests.csproj --collect:"XPlat Code Coverage" --results-directory ./TestResults

    - name: Convert coverage to Cobertura format
      run: |
        dotnet tool install --global dotnet-reportgenerator-globaltool
        export PATH="$PATH:/home/runner/.dotnet/tools"
        reportgenerator -reports:"./TestResults/**/coverage.cobertura.xml" -targetdir:"coveragereport" -reporttypes:Cobertura

    - name: List coverage files
      run: ls -R coveragereport

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coveragereport/Cobertura.xml
